### PR TITLE
FUSETOOLS2-440 - upgrade AtlasMap to 2.0.1

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by lhein** [comment]
some tests appear to be broken. working on it

**Comment by lhein** [comment]
multiple issues:
# the title of the webapp changed from using `AtlasMap` to `Atlasmap`
# a test adm file downloaded from a github tag is no longer available

**Comment by lhein** [comment]
fixed the test failures for the non-ui tests. ui-tests are broken too.

**Comment by lhein** [comment]
to fix the ui tests I had to upgrade vscode-extension-tester to 3.0.0. Thanks to QE for providing the fix.

**Comment by lhein** [comment]
I think the upgrade of the extension tester might fix the other open PR too.

**Comment by apupier** [comment]
oups, misclicked for "closing pull request. I reopened it

**Comment by apupier** [comment]
seems the 2.0.1 has not implemented several pages. see https://chat.google.com/room/AAAAuxCb91U/EjLudS5piig

I would propose to wait that it is implemented to merge in master. it remains important to continue testing integration.

**Comment by apupier** [comment]
covered by https://github.com/jboss-fuse/vscode-atlasmap/pull/373 as additional and simultaneous modifications were required

**Pull request closed without merging**
