### PR TITLE
Load Atlasmap directly in the webview

### LINKED ISSUE #371: Embedding Atlasmap using an iframe breaks Atlasmap
XRef https://github.com/atlasmap/atlasmap/issues/2054

### PR DESCRIPTION
**Pull request by riccardo-forina**
It looks like iframes inside a webview are buggy/limited. This loads
Atlasmap directly inside the webview skipping the iframe step.

Fixes #371

### CODE REVIEW

**Comment by apupier** [comment]
I don't understand the exact impact of doing this kind of change.

can you provide more information why the iframe should be avoided in VS Code please?

The examples to have the webview working with VS Code Online (and so Eclipse Che) is using an IFrame https://code.visualstudio.com/api/advanced-topics/remote-extensions#option-1-use-asexternaluri Is it changing something to load directly inside the webview on this point?

**Comment by riccardo-forina** [comment]
Atlasmap embedded in an (electron?) iframe shows quirks that are specific to this kind of embedding: clicks that are not registered, drag&drop not working, perhaps more. These quirks aren’t solvable by Atlasmap itself, because are specific to this environment.

The solution to remove these quirks is to avoid using an iframe and load Atlasmap directly in the webview. How it’s done it’s described in the comments. Nothing changes in how Atlasmap is run inside VSC, the port mapping is still there (if I understood your comment).

**Comment by apupier** [comment]
with this PR on the Angular based UI, I have a blank page. Just the header.

**Comment by riccardo-forina** [comment]
Just tested with https://search.maven.org/artifact/io.atlasmap/atlasmap-standalone/2.0.3/jar and it works for me. I haven't tested this with the Angular version, probably it doesn't work with that (and will not be fixed).

**Comment by riccardo-forina** [comment]
It looks like the issue with the Angular version is the failure in setting up the router since the electron iframe is a data iframe and not a url one, which doesn't allow for navigation. It's unfortunate since AtlasMap doesn't use any routing neither in the Angular version nor in the React one, but the Angular version starts the router up anyway.

image

**Comment by apupier** [comment]
no more using the iframe is causing the dropdown marker to not show up in "Create Property"
Screenshot from 2020-06-03 11-50-29

it is working fine on Chrome and with VS Code when using an iframe

**Comment by apupier** [comment]
it is fine that it is not working with Angular. it is just that we cannot merge it independently than upgrading the AtlasMap version.

**Comment by riccardo-forina** [comment]
> no more using the iframe is causing the dropdown marker to not show up in "Create Property"
> it is working fine on Chrome and with VS Code when using an iframe

Thanks, the CSP wasn't allowing for `data:` images. Updated to allow them.

**Comment by apupier** [comment]
- not spotted specific issue to VS Code
- side-note: tried with Che: unfortunately it is still causing a totally blank page. But fortunately now there is an error that we will be able to investigate further (timed out trying to access the index.html `VM114:3 GET https://routep6oue0pw-apupier-che.b542.starter-us-east-2a.openshiftapps.com:8585/index.html net::ERR_TIMED_OUT
` )

I will add the AtlasMap version upgrade to this PR as both are mandatory to have things working.

**Comment by apupier** [comment]
argh i cannot push to this branch.

@riccardo-forina Do you prefer to rebase and add the version upgrade yourself? or to "allow maintainers to edit the branch" (which should be somewhere in your UI of github)? Or that i create another PR?

**Comment by riccardo-forina** [comment]
Done. Not sure why you can't push there, I have no special settings and I usually get PRs against my forks

**Comment by apupier** [comment]
Thank you very much for this PR

**Pull request merged**
