### PR TITLE
Fix UI Tests NoSuchElement errors

### PR DESCRIPTION
**Pull request by djelinek**
Signed-off-by: Dominik Jelinek <djelinek@redhat.com>

### CODE REVIEW

**Comment by djelinek** [comment]
Related to #212

**Comment by djelinek** [comment]
Hi @apupier, I resolved your note, thank you for your review.

**Comment by djelinek** [comment]
@apupier Could you please also merge it? I have no rights to do that :(

**Comment by apupier** [comment]
will wait the 24h rules sicne opening (or that Lars and Brian both acknowledge)

and we will see how to add you in jboss-fuse organization

**Comment by djelinek** [comment]
Sure, thank you.

**Pull request merged**
