### PR TITLE
Open browser on a specific URL which is the default one when starting

### PR DESCRIPTION
**Pull request by apupier**
Atlasmap

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
Atlasmap needs to be launched locally on port 8585 which is the default one when launching `mvn -Pitests  spring-boot:run` as indicated as the fastest way to launch the standalone version.

see https://drive.google.com/open?id=1uoZ8MbA8yRAzBk2irDFEBhwuG9KvzC_Y

**Comment by lhein** [comment]
How about naming the command "Open AtlasMap in external browser" or similar so it becomes more clear its summoning an external browser instead of using an internal view? I'd consider this PR a "Plan B" if we fail to deliver the webapi extension.

**Comment by apupier** [comment]
> How about naming the command "Open AtlasMap in external browser" or similar so it becomes more clear its summoning an external browser instead of using an internal view?

the command name is "Open Atlas Map in default system browser", I feel "default system browser" is clearer than just "external browser".

**Comment by apupier** [comment]
> I'd consider this PR a "Plan B" if we fail to deliver the webapi extension.

given the slow progress on using webview API, I think that opening an external browser as first iteration is bringing a lot of value on short term. It is what I proposed as first iteration several times and PM were fine with it.
Switching to opening webview API will be a matter of removing very few lines of "opening in default system browser" code.

**Pull request merged**
