### PR TITLE
allow to specify a port to use for local atlasmap launch #18

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by lhein** [comment]
Users can now enter a port to use for local atlasmap instance launch. The port entered will be checked for availability. If available, the atlasmap instance will be fired up, otherwise an error message will be shown.

**Comment by lhein** [comment]
merged ur PR manually and added the missing assert dev dep

**Comment by apupier** [comment]
Shouldn't we close this PR?

**Comment by lhein** [comment]
closed because #47 will make this one obsolete

**Pull request closed without merging**
