### PR TITLE
fixed messed up dependencies which cause the vsix to be broken #70

### PR DESCRIPTION
**Pull request by lhein**
this PR is based on #68

### CODE REVIEW

**Comment by apupier** [comment]
@lhein Can you rebase this PR on master please?

**Comment by lhein** [comment]
done

**Comment by lhein** [comment]
yeah, but I am not sure how to fix that. For the dependency problem there are node modules which can check your project. see for instance https://www.npmjs.com/package/depcheck

**Comment by apupier** [comment]
good pointers, maybe we can integrate it in our travis build. I created https://github.com/jboss-fuse/vscode-atlasmap/issues/75 to work on that.

**Pull request merged**
