### PR TITLE
Bumped version of AtlasMap to v1.39.3

### PR DESCRIPTION
**Pull request by paoloantinori**

### CODE REVIEW

**Comment by lhein** [comment]
What is new in that version? Is it still WebView API compliant?

**Comment by apupier** [comment]
> What is new in that version? Is it still WebView API compliant?

it is fixing https://github.com/atlasmap/atlasmap/issues/748 and https://github.com/atlasmap/atlasmap/issues/752

it improves the WebView API integration

**Comment by paoloantinori** [comment]
Good question. We don't have a release log yet, and we are not even paying
to much attention to version semantics, but we can probably already keep
track of a central place to store an high level channeling.

I suggest in a plain mark down for, in the main folder

**Comment by lhein** [comment]
That has to be done in the AtlasMap project.

**Pull request merged**
