### PR TITLE
FUSETOOLS2-1267 - Provide opt-in telemetrics for usage

### PR DESCRIPTION
**Pull request by apupier**
allows to provide this kind of reports https://app.woopra.com/project/test.vscode/analyze/report/trends/hdsehizqub or https://app.woopra.com/project/test.vscode/analyze/report/trends/dxsfyikk4o

### CODE REVIEW

**Comment by lhein** [comment]
We got an additional option for usage tracking which is the right click context menu on ADM files which allows to `Open in AtlasMap`.

**Comment by apupier** [comment]
> We got an additional option for usage tracking which is the right click context menu on ADM files which allows to `Open in AtlasMap`.

this is not a specific command. It is using the atlasmap.start command see https://github.com/jboss-fuse/vscode-atlasmap/blob/64bfa61634edc4a72b1fbdc05f21163c9373e107/package.json#L60

**Comment by lhein** [comment]
It only calls it if its not yet started. And it hands over a file path.

**Comment by apupier** [comment]
> It only calls it if its not yet started. And it hands over a file path.

I do not understand.

Either through command palette or through contextual menu on right-click, the command is called. it is after inside the command that there is a difference of treatment of the request. But [the tracking event is sent at the very beginning in all cases](https://github.com/jboss-fuse/vscode-atlasmap/pull/675/files#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R45). Having the file path as parameter or not is not checked to send the tracking event.

**Comment by lhein** [comment]
My suggestion was  basically to also track if its called with an adm file or not.

**Comment by apupier** [comment]
Definitely a possible improvement but I preferred to not do it in this Pull Request as the effort of implementation compared to added-value is far lower than with this current scope.

**Review by lhein — APPROVED** [review]
fair enough

**Pull request merged**
