### PR TITLE
FUSETOOLS2-770 - bump AtlasMap version to 2.1.0

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by lhein** [comment]
@djelinek Hi Dominik. Can you please check this broken UI test? https://travis-ci.org/github/jboss-fuse/vscode-atlasmap/builds/733764401#L846 

Thank you

**Comment by apupier** [comment]
@dependabot rebase

**Comment by lhein** [comment]
@apupier Don't call me dependabot ;)

**Review by apupier — DISMISSED** [review]
- the changelog needs to be updated
- lines are drawn completely out of the correct place
Screenshot from 2020-10-13 10-05-26
- tooltips are put at the wrong place
Screenshot from 2020-10-13 10-06-36
- toolti can be overriding each other (at the worng place)
Screenshot from 2020-10-13 10-08-16

stiopping here...
There is a need a full pass on UI. Checking what is specific to VS Code and what is not generic to AtlasMap.

**Comment by riccardo-forina** [comment]
You probably don't have the default 100% zoom for the view. Try resetting it in View -> Appearance -> Reset Zoom

Related issue https://github.com/atlasmap/atlasmap/issues/2042

**Review by apupier — DISMISSED** [review]
- missing changelog

**Review by apupier — APPROVED** [review]

**Review by bfitzpat — APPROVED** [review]

**Pull request merged**
