### PR TITLE
Make the viewport fluid.

### LINKED ISSUE #354: Viewport size should be fluid
Currently Atlasmap is embedded in an iframe with a fixed height of 900px. Atlasmap has been designed to work using the available space, so the viewport should be fluid.

### PR DESCRIPTION
**Pull request by riccardo-forina**
Fixes #354

### CODE REVIEW

**Comment by apupier** [comment]
I think the CI errors are due to breakage compatibility between vscode-extension-tester and latest VS Code release of yesterday. So unrelated to these changes.

**Comment by apupier** [comment]
the height of 900 was provided to be compatible with Eclipse Theia. will require a check on Theia/Che side.see comments on commit https://github.com/jboss-fuse/vscode-atlasmap/commit/59c4e25b76fff09ba518d16b75530773caa6ac03

**Comment by riccardo-forina** [comment]
Will you test it? Or should I?

**Comment by apupier** [comment]
Just looked more carefully to the commit message and gathering what I can remember.

The part that was done for Theia compatibility was to put inside an iframe. it was inside VS Code itself that the page wasn't displayed correctly without the height set to an absolute value.

To test inside Theia, it needs to be on gitpod with special rights that we don't have. They are removing some security that was allowing to make it visible. In pure Theia and Che, it is not displaying at all, so cannot be checked.

All that said, the good news is that it means we only need to test inside VS Code that it is displayed well.

**Comment by riccardo-forina** [comment]
Test how? Manually?

**Comment by apupier** [comment]
> Test how? Manually?

Yes, I have testing manually in mind. I don't have ideas on a way to automate test for this kind of stuff (in an easy and maitainable way).

**Comment by apupier** [comment]
works fine both with Angular and React:

Screenshot from 2020-05-14 14-07-02
Screenshot from 2020-05-14 14-02-50

I will rebase on master to have tests running fully on CI without error

**Pull request merged**
