### PR TITLE
Override padding style from VS Code to match AtlasMap one #69

### PR DESCRIPTION
**Pull request by apupier**
it allows to take the whole space in UI

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
image

**Comment by apupier** [comment]
@igarashitm @pleacu Can you review it please?
Can it affect some parts of AtlasMap UI?

**Comment by lhein** [comment]
@igarashitm @pleacu some feedback would be really good before merging this PR.

**Comment by igarashitm** [comment]
Hmm doesn't look like causing major problem though, I can't guarantee there's no problem... I think it's rather let's try and see kind of thing.

**Comment by apupier** [comment]
> Hmm doesn't look like causing major problem though, I can't guarantee there's no problem... I think it's rather let's try and see kind of thing.

web development is scary :s

**Pull request merged**
