### PR TITLE
upgrading to AtlasMap 1.40.2

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by apupier** [comment]
one test has failed 2 times in a row

```
1) Start AtlasMap Command Tests with browser type: Internal
       Test import of ADM file with running server:
     Error: connect ECONNREFUSED 127.0.0.1:8585
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
```

I'm also still reproducing the two previous regressions atlasmap/atlasmap#1029 and atlasmap/atlasmap#1028

I double-checked that the atlasmap-standalone file in my workspace has been updated

**Comment by lhein** [comment]
the ECONNREFUSED error is unrelated to this PR. It occurs every once in a while, sometimes more often, sometimes less often. It has to be investigated and fixed in a separate PR.

For https://github.com/atlasmap/atlasmap/issues/1029 I tested it several times in a row manually and it did not occur on my machine so far.

Anyways, please report those issues in the appropriate issue manager at atlasmap project. This PR is about the upgrade of the AtlasMap version.

**Comment by apupier** [comment]
argh, the previously found regression are available only on the master, so not in 1.40.2. We still need to wait for a release done from the master

**Comment by lhein** [comment]
Closing the PR because 1.40.2 introduces issues. Another PR will be created once there is a working version.

**Pull request closed without merging**
